version: '3.9'

services:
  postgres:
    hostname: postgres
    image: postgres:latest
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    networks:
      - app-network
  app:
    hostname: app
    container_name: go-gin-clean-starter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${GOLANG_PORT}:8888
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - app-network

volumes:
  app_vol:

networks:
  app-network:
    driver: bridge
